# Generated by Django 5.0.6 on 2026-08-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Kichik sarlavha / Izoh')),
                ('tag', models.CharField(default='Aksiya', max_length=50, verbose_name='Teg (masalan: Aksiya, Yangilik)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner rasmi')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Rasm havolasi (tashqi URL)')),
                ('button_text', models.CharField(default='Xarid qilish', max_length=50, verbose_name='Tugma matni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.category', verbose_name="Bog'langan kategoriya")),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
