# Generated by Django 5.0.6 on 2026-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Havola / Link (masalan: https://t.me/... yoki screen:cart)'),
        ),
    ]
