# Generated by Django 5.0.6 on 2026-08-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '🆕 Yangi'), ('confirmed', '✅ Tasdiqlangan'), ('delivering', '🚚 Yetkazilmoqda'), ('done', '✔️ Yakunlangan'), ('cancelled', '❌ Bekor qilingan')], default='new', max_length=20, verbose_name='Holat')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('payme', 'Payme'), ('click', 'Click')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('address_text', models.CharField(max_length=500, verbose_name='Manzil matni (snapshot)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kenglik (snapshot)')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Uzunlik (snapshot)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Jami narx (so'm)")),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='Manzil (FK)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi (snapshot)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Birlik narxi (snapshot, so'm)")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Mahsulot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit', verbose_name="O'lchov birligi (snapshot)")),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
    ]
