# Generated by Django 5.0.6 on 2026-08-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name="To'liq ism")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uy', max_length=100, verbose_name='Manzil nomi')),
                ('address_text', models.CharField(max_length=500, verbose_name='Manzil matni')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kenglik (lat)')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Uzunlik (lon)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
    ]
