# Generated by Django 5.0.6 on 2026-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Kenglik (lat)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Uzunlik (lon)'),
        ),
    ]
